apiVersion: v1
kind: Namespace
metadata:
  name: shipping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: shipping
  labels:
    app: shipping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: 146624863079.dkr.ecr.ap-south-1.amazonaws.com/demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CART_ENDPOINT
              value: "cart:8080"      # update if your cart service name/port is different
            - name: DB_HOST
              value: "mysql"          # update to your MySQL service name
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: shipping
  labels:
    app: shipping
spec:
  selector:
    app: shipping
  ports:
    - name: http
      port: 8080        # service port inside cluster
      targetPort: 8080  # containerPort in the pod
  type: ClusterIP       # change to LoadBalancer if you want direct external access
